name: "* Publish Test Domain Services"

on:
  push:
    branches:
      - test

jobs:
  publish_test_domain_services:
    name: Publish Test Domain Services
    uses: ./.github/workflows/publish-ffxivvenues-domain-services.yml
    with:
      branch: test
      tag: test        
    secrets: inherit
