name: "* Publish Production Domain Services"

on:
  push:
    branches:
      - main

jobs:
  publish_production_domain_services:
    name: Publish Production Domain Services
    uses: ./.github/workflows/publish-domain-services.yml
    with:
      branch: main
      tag: latest
    secrets: inherit