name: Publish Domain Services

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to publish from
        required: true
        type: string
        default: main
      tag:
        description: Tag to publish with
        required: true
        type: string
        default: latest
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: main
      tag:
        required: true
        type: string
        default: latest
    secrets:
      docker_username:
        required: true
      docker_access_token:
        required: true

jobs:
  publish_for_platforms:
    strategy:
      matrix:
        application:
          - name: ApiGateway
            path: FFXIVVenues.ApiGateway
            image: ffxivvenues.apigateway
          - name: FlagService
            path: FFXIVVenues.FlagService
            image: ffxivvenues.flagservice
          - name: OGCardService
            path: FFXIVVenues.OGCardService
            image: ffxivvenues.ogcardservice
        platform:
          - name: amd64
            runner: ubuntu-24.04
            alias: linux/amd64
            tag: amd64
          - name: arm64
            runner: ubuntu-24.04-arm
            alias: linux/arm64
            tag: arm64

    name: Publish ${{ matrix.application.name }} for ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and push API Gateway docker image
        run: |
          docker build --push --platform ${{ matrix.platform.alias }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.application.image }}:${{ inputs.tag }}-${{ matrix.platform.tag }} \
          -f ${{ matrix.application.path }}/Dockerfile .


  publish_multiplatform_manifest:
    strategy:
      matrix:
        include:
          - name: ApiGateway
            image: ffxivvenues.apigateway
          - name: FlagService
            image: ffxivvenues.flagservice
          - name: OGCardService
            image: ffxivvenues.ogcardservice

    name: Publish ${{ matrix.name }} multiplatform manifest
    runs-on: ubuntu-latest
    needs: publish_for_platforms

    steps:
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Create and push manifest
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ inputs.tag }} \
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ inputs.tag }}-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ inputs.tag }}-arm64